# 2023计算物理学A 第一次习题课 
## 第二部分
胡佳妮 2023.10.17
### 1. numpy矩阵乘法
数组（np.array）是有序排列的【同类数据元素】的集合  
矩阵（np.matrix）是一个按照【二维】排列的【复数】集合

In [56]:
import numpy as np

In [57]:
a=[[1,2,3],[4,5,6]]
b=[1,2,3]
c=[[1],[2],[3]]

#### 1.1 np.matrix

In [58]:
a_M=np.matrix(a)
b_M=np.matrix(b)
c_M=np.matrix(c)

In [59]:
#矩阵相乘
print(a_M*c_M)
(a_M*c_M).shape

[[14]
 [32]]


(2, 1)

In [60]:
#矩阵相乘
a_M@c_M

matrix([[14],
        [32]])

In [61]:
#矩阵相乘
np.dot(a_M,c_M)

matrix([[14],
        [32]])

In [62]:
#矩阵相乘
np.matmul(a_M,c_M)

matrix([[14],
        [32]])

In [64]:
#元素相乘
np.multiply(a_M,c_M) #因为是元素相乘，所以会报错

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [65]:
np.multiply(a_M,b_M)

matrix([[ 1,  4,  9],
        [ 4, 10, 18]])

#### np.array

In [66]:
a_A=np.array(a)
b_A=np.array(b)
b_A

array([1, 2, 3])

b_A不是矩阵，np.array([[1,2,3]])或np.matrix([1,2,3])才算

In [67]:
#元素相乘
a_A*b_A

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [68]:
#矩阵相乘
print(a_A@b_A)
(a_A@b_A).shape

[14 32]


(2,)

In [69]:
d=np.array([[1],[2]])
d.shape

(2, 1)

np.array 取第一列A[:, 0] 返回的不是矩阵, shape是没有列的维度的(例如(2,) 而不是(2,1)), 而np.matrix则是列向量形式的矩阵(符合预期)

In [70]:
#矩阵相乘
np.dot(a_A,b_A)

array([14, 32])

In [71]:
#矩阵相乘
np.matmul(a_A,b_A)

array([14, 32])

In [72]:
#元素相乘
np.multiply(a_A,b_A)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

## 2. pandas初步
### 2.1 pandas概况
Pandas的两大主要数据结构是Series和DataFrame。DataFrame是一种二维数据表，每列可以是不同数据类型，每一个列是一个series。    
Series是带标签的一维数组，可储存整数、浮点数、字符串等类型的数据，由纵向排列的values和index组成，可以通过字典方式，key获取value。
### 2.2 数据表内容生成

In [73]:
import pandas as pd

#### 2.2.1 建立数据表
pd.DataFrame

In [101]:
#直接生成
a=[['2','4','5'],['5','5','2']] 
df=pd.DataFrame(a,columns=['A','B','C'],index=['a','b']) # 如果不加columns（列）和index（行），则默认从0，1，2...
print(df)
df2=pd.DataFrame(np.random.randn(5,3),index=pd.date_range('20230331',periods=5),columns=["Alice","Bob","Cathy"]) #"periods="不可省了
print(df2)

#字典创建
dic3={'school':['PKU','PKU','THU'],'year':['2022','2021','2020'],'scores':[20,30,4]} #创建series
df3=pd.DataFrame(dic3,index=['a','b','c'])
print(df3)

   A  B  C
a  2  4  5
b  5  5  2
               Alice       Bob     Cathy
2023-03-31 -0.068994 -1.270421 -0.565206
2023-04-01  0.317719 -0.774351 -1.983462
2023-04-02  0.955290  1.368207  0.605859
2023-04-03 -0.813152  0.175058 -2.085859
2023-04-04  0.348438  0.835740  0.995328
  school  year  scores
a    PKU  2022      20
b    PKU  2021      30
c    THU  2020       4


#### 2.2.2 时间索引生成
pd.date_range用于生成固定频率的时间索引
pd.date_range(stat=xx,end=xx,periods=xx,freq=xx)前三个必须要写两个，periods为数量，freq默认D，也可M,H,5H...）

In [102]:
import pandas as pd
a=[['2','4','5'],['5','5','2'],['4','7','8']]
b=pd.date_range('20230331','20230402')
df=pd.DataFrame(a,index=b)
print(df)

            0  1  2
2023-03-31  2  4  5
2023-04-01  5  5  2
2023-04-02  4  7  8


##### 补充：datetime模块

In [103]:
from datetime import datetime,time,timedelta

(1)时间获取

In [104]:
#获取当前时间
current_time1=datetime.today()
print(current_time1)
current_time2=datetime.now()
print(current_time2)
#都是报现在时间
#继续.date()是提取年月日；.()是提取时分秒；。hour()，day,second,year...
type(current_time1)

2023-10-16 21:52:43.818375
2023-10-16 21:52:43.819375


datetime.datetime

（2）格式转换

In [105]:
#日期转字符串
datetime_str=current_time1.strftime("%Y-%m-%d") #strftime指定格式化的字符输出。%Y四位数的年份，%y两位数的年份
print(datetime_str)

#字符串转时间
datetime_dt=datetime.strptime("2020-12-31","%Y-%m-%d")
print(datetime_dt)
dt=pd.to_datetime("2021-12-30")
print(dt)

2023-10-16
2020-12-31 00:00:00
2021-12-30 00:00:00


（3）时间增量

In [106]:
end_date=datetime.now().date()
start_date=end_date-timedelta(days=365) #timedelta表示时间差值，不能先化成字符串再减。days可以换成其他单位
#timedata()与pd.Timedelta()等效
print(start_date)

d1=datetime(2018,10,31)
d2=datetime(2019,2,25)
interval0=d2-d1
print(interval0) #当然也可以.days()等。不是年或者月的整数时调用会报错，但可以用days()/365

# 计算两个时点之间相差多少分钟
t1 = datetime(2018, 10, 31, 10, 30, 1)
t2 = datetime(2018, 10, 31, 15, 24, 43)
interval = t2 - t1
print(interval.total_seconds()/60, 'minutes')

2022-10-16
117 days, 0:00:00
294.7 minutes


### 2.3 数据表内容处理
#### 2.3.1 内容读取

In [107]:
#区域读取
print(df2)
a=df2.iloc[2:,1:] #df.iloc是位置读取，[行，列],可以有负数
print(a)

b=df2.loc['2023-04-01',df2.columns[:2]] #df.loc是名称读取。当只有一行时不返回表格式样
#若取整行或者整列，可以只写一个名字
print(b)
print(df2.index[0],df2.columns[1]) #不是数据，而是名称的字符串

               Alice       Bob     Cathy
2023-03-31 -0.068994 -1.270421 -0.565206
2023-04-01  0.317719 -0.774351 -1.983462
2023-04-02  0.955290  1.368207  0.605859
2023-04-03 -0.813152  0.175058 -2.085859
2023-04-04  0.348438  0.835740  0.995328
                 Bob     Cathy
2023-04-02  1.368207  0.605859
2023-04-03  0.175058 -2.085859
2023-04-04  0.835740  0.995328
Alice    0.317719
Bob     -0.774351
Name: 2023-04-01 00:00:00, dtype: float64
2023-03-31 00:00:00 Bob


In [108]:
#行列读取
#列读取
print(df3)
school=df3.school #或者df3["school"],总之和字典一样.上一种方式字典没有。index不能用这两种方式索引，只能用区域读取
print (school)

#行读取
A=df3.loc["a"]
print(A)

#有数值排列的行列读取
from datetime import datetime
S=df2.loc[datetime(2023,4,2):]#这个非常常用
print(S)

dp=pd.DataFrame(dic3)
print(dp)
print(dp.loc[1:])#但仍然不支持负数，本质还是检索的内容而非位置

  school  year  scores
a    PKU  2022      20
b    PKU  2021      30
c    THU  2020       4
a    PKU
b    PKU
c    THU
Name: school, dtype: object
school     PKU
year      2022
scores      20
Name: a, dtype: object
               Alice       Bob     Cathy
2023-04-02  0.955290  1.368207  0.605859
2023-04-03 -0.813152  0.175058 -2.085859
2023-04-04  0.348438  0.835740  0.995328
  school  year  scores
0    PKU  2022      20
1    PKU  2021      30
2    THU  2020       4
  school  year  scores
1    PKU  2021      30
2    THU  2020       4


In [109]:
#首尾读取
head=df3.head(2)#前两行
print(head)
tail=df3.tail(2)#后两行
print(tail)

  school  year  scores
a    PKU  2022      20
b    PKU  2021      30
  school  year  scores
b    PKU  2021      30
c    THU  2020       4


#### 2.3.2位置查找
.idxmax()

#### 2.3.3 内容修改

In [110]:
#赋值修改
df2.loc[df2.index[3],df2.columns[0]]=1 
df2.iloc[1,2]=2
print(df2)

               Alice       Bob     Cathy
2023-03-31 -0.068994 -1.270421 -0.565206
2023-04-01  0.317719 -0.774351  2.000000
2023-04-02  0.955290  1.368207  0.605859
2023-04-03  1.000000  0.175058 -2.085859
2023-04-04  0.348438  0.835740  0.995328


#### 补充：NA值处理
.dropna(）   
.fillna()

#### 2.3.4 内置计算

In [122]:
#max,min,mean,median
print(df2)
df2['min']=df2[df2.columns[:1]].min(axis=1) #df[]里面是名称，牢记DF本质是字典！
print(df2)
print(df2.Alice.max())

#pct_change相邻两天百分比变化（收益率）
print(df2.Alice.pct_change()) #用收盘价

#std标准差
daily=df2.Alice.pct_change().std()
print(daily)

#corr相关性(r[-1,1])
r=df2[["Alice","Bob"]].corr()
print(r)

               Alice       Bob     Cathy       min
2023-03-31 -0.068994 -1.270421 -0.565206 -0.068994
2023-04-01  0.317719 -0.774351  2.000000  0.317719
2023-04-02  0.955290  1.368207  0.605859  0.955290
2023-04-03  1.000000  0.175058 -2.085859  1.000000
2023-04-04  0.348438  0.835740  0.995328  0.348438
               Alice       Bob     Cathy       min
2023-03-31 -0.068994 -1.270421 -0.565206 -0.068994
2023-04-01  0.317719 -0.774351  2.000000  0.317719
2023-04-02  0.955290  1.368207  0.605859  0.955290
2023-04-03  1.000000  0.175058 -2.085859  1.000000
2023-04-04  0.348438  0.835740  0.995328  0.348438
1.0
2023-03-31         NaN
2023-04-01   -5.604995
2023-04-02    2.006716
2023-04-03    0.046803
2023-04-04   -0.651562
Freq: D, Name: Alice, dtype: float64
3.2379632880162066
          Alice       Bob
Alice  1.000000  0.721275
Bob    0.721275  1.000000


In [126]:
#累计最大值
print(df2.Alice.cummax())
#累计乘法
print(df2.Alice.cumprod())

2023-03-31   -0.068994
2023-04-01    0.317719
2023-04-02    0.955290
2023-04-03    1.000000
2023-04-04    1.000000
Freq: D, Name: Alice, dtype: float64
2023-03-31   -0.068994
2023-04-01   -0.021921
2023-04-02   -0.020941
2023-04-03   -0.020941
2023-04-04   -0.007297
Freq: D, Name: Alice, dtype: float64


#### 2.3.5 数据合并
pd.merge()，pd.contact()，.join()

In [123]:
#pd.merge()
df2_add=pd.DataFrame(np.random.randn(5),index=pd.date_range('20230331',periods=5),columns=["David"]) 
print(df2_add)
df2_new=pd.merge(df2,df2_add,on=pd.date_range('20230331',periods=5))
#对齐date添加到一个表中，,suffixes=("_xxx")在column后缀名加下划线标识
print(df2_new)

               David
2023-03-31 -0.419200
2023-04-01  0.386146
2023-04-02 -1.836189
2023-04-03 -0.560856
2023-04-04  0.128600
       key_0     Alice       Bob     Cathy       min     David
0 2023-03-31 -0.068994 -1.270421 -0.565206 -0.068994 -0.419200
1 2023-04-01  0.317719 -0.774351  2.000000  0.317719  0.386146
2 2023-04-02  0.955290  1.368207  0.605859  0.955290 -1.836189
3 2023-04-03  1.000000  0.175058 -2.085859  1.000000 -0.560856
4 2023-04-04  0.348438  0.835740  0.995328  0.348438  0.128600


.join(other, on=None, how=’left’, lsuffix=”, rsuffix=”, sort=False)

通过索引或者指定的列连接一个或多个的DataFrame，底层是merge，但merge只能横向联结，参数包括： 

* other：代表需要合并的一个或者多个DataFrame，或者带有名字的Series
* on：列名称，或者列名称的列表/元组，或者类似形状的数组；默认使用索引连接
* how：连接方式包括‘left',‘right',‘outer’,‘inner’4种连接方式；默认使用左连接
* lsuffix：左DataFrame中重复列的后缀, 注意是重复列添加后缀，不是所有的列
* rsuffix：右DataFrame中重复列的后缀，注意是重复列添加后缀，不是所有的列
* sort：按照字典顺序对结果在连接键上排序；如果为False，连接键的顺序取决于连接类型（关键字)
     
pd.concat()    
更多是物理拼接，不像前两者是通过索引或者列识别

#### 2.3.6 数据分组

.groupby()就是按xx分组, 标准用法为: <br />
        ```DataFrame.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, **kwargs)``` <br />
先关注by参数，表示根据哪一列或者哪几列分组，如果没有设置则默认按照索引分组，其余参数较为繁杂，可以使用默认值。<br />

最基本的就是组内计数, 求和, 求均值, 求方差。例如 <br />
        ```dataframe.groupby('race')['age'].mean() ```<br />
此外，也可以用apply或者agg方法传入自定义的函数进行运算，例如 <br />
       ```dataframe.groupby('race')['age'].apply(lambda x: max(x) - min(x))```

##### 2.3.7 极值截断


In [131]:
confidence_level = 0.05
thresh = df2.quantile([confidence_level, 1 - confidence_level])
print(thresh)

         Alice       Bob     Cathy       min
0.05  0.008348 -1.171207 -1.781729  0.008348
0.95  0.991058  1.261714  1.799066  0.991058


In [133]:
print(df2.Alice.clip(-0.5,0.5))

2023-03-31   -0.068994
2023-04-01    0.317719
2023-04-02    0.500000
2023-04-03    0.500000
2023-04-04    0.348438
Freq: D, Name: Alice, dtype: float64


一个pandas有趣实例，见课堂演示（狗头jpg.)